version: '3.8'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=django-insecure-$$)i3kc+1xwi_-ykba#ne+ggkv=jcmgm5c#e9*$$-p7z3f+owpre'
      - 'DJANGO_DEBUG=True'
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
volumes:
  postgres_data:
