# Generated by Django 4.2.1 on 2023-05-12 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_id_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6757e64c-46b0-45ca-bc5c-15ca0e1b2b32'), editable=False, primary_key=True, serialize=False),
        ),
    ]
