# Generated by Django 4.2.1 on 2023-05-14 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_alter_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4460b34b-9c5d-4d1e-8561-b8da8ebefbb6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
