# Generated by Django 4.2.1 on 2023-05-19 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_id_book_id_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('283479f7-1b75-40ee-acb5-2cc456ce881b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
